import type { LeadCandidateInput } from "./types";
import { buildOutreachEmail, type OutreachEmailInput } from "./emailTemplates";

// Subject + body from the shared high-signal outreach engine; `angle` is the
// lead-specific friction observation inserted before the CTA.
function outreach(input: OutreachEmailInput) {
  const { subject, bodyHtml } = buildOutreachEmail(input);
  return { emailSubject: subject, emailBodyHtml: bodyHtml };
}

const defaults = {
  status: "review" as const,
  openStatus: "open" as const,
  leadSource: "Researched seed list",
  notes: null,
  reviewedAt: null,
  approvedPipelineContactId: null,
  emailedAt: null,
};

export const researchedSeedLeads: LeadCandidateInput[] = [
  {
    _id: "lead-candidate-richmond-ballet",
    ...defaults,
    businessName: "Richmond Ballet",
    niche: "Performing arts, education, memberships, events",
    city: "Richmond",
    region: "Richmond",
    address: "407 East Canal Street, Richmond, VA 23219",
    phone: "(804) 344-0906",
    email: null,
    contactUrl: "https://richmondballet.com/contact-us/",
    website: "https://richmondballet.com/",
    sourceUrl: "https://richmondballet.com/",
    fitScore: 82,
    currentSnapshot: "Active performing arts organization with school, performances, ticketing, donations, rentals, and news signup.",
    gapAssessment: "Multiple user paths appear spread across tickets, school, donations, rentals, and events.",
    howCel3CanHelp: "A cleaner audience portal and event/school dashboard could connect ticketing, classes, donations, and follow-up in one system.",
    ...outreach({
      businessName: "Richmond Ballet",
      city: "Richmond",
      region: "Richmond",
      niche: "Performing arts, education, memberships, events",
      angle:
        "From the outside, one family can be a ticket buyer, a school parent, a donor, and a rental inquiry all at once — and each of those runs through a different door, so reconciling them almost certainly falls on staff.",
    }),
  },
  {
    _id: "lead-candidate-studio-two-three",
    ...defaults,
    businessName: "Studio Two Three",
    niche: "Arts nonprofit, workshops, memberships, community programs",
    city: "Richmond",
    region: "Richmond",
    address: "109 W 15th Street, Richmond, VA 23224",
    phone: null,
    email: null,
    contactUrl: "https://studiotwothree.org/pages/contact",
    website: "https://studiotwothree.org/",
    sourceUrl: "https://studiotwothree.org/",
    fitScore: 78,
    currentSnapshot: "Active arts organization with classes, membership, events, shop, and community programs.",
    gapAssessment: "Workshop, member, donor, and retail paths create a strong case for better operational visibility.",
    howCel3CanHelp: "A member/class operations console could centralize signups, attendance, donor touchpoints, and program performance.",
    ...outreach({
      businessName: "Studio Two Three",
      city: "Richmond",
      region: "Richmond",
      niche: "Arts nonprofit, workshops, memberships, community programs",
      angle:
        "Workshops, memberships, the shop, and community programs each leave their own admin trail, which usually means several exports before anyone can see one member clearly.",
    }),
  },
  {
    _id: "lead-candidate-visual-arts-center-richmond",
    ...defaults,
    businessName: "Visual Arts Center of Richmond",
    niche: "Arts education, classes, memberships, exhibitions",
    city: "Richmond",
    region: "Richmond",
    address: "1812 W Main Street, Richmond, VA 23220",
    phone: "(804) 353-0094",
    email: null,
    contactUrl: "https://www.visarts.org/contact/",
    website: "https://www.visarts.org/",
    sourceUrl: "https://www.visarts.org/",
    fitScore: 80,
    currentSnapshot: "Active arts center with classes, events, exhibitions, youth programs, and memberships.",
    gapAssessment: "Class discovery and engagement could benefit from more personalized navigation and post-registration follow-up.",
    howCel3CanHelp: "A class/member dashboard could help surface enrollment trends, automate reminders, and clarify program performance.",
    ...outreach({
      businessName: "Visual Arts Center of Richmond",
      city: "Richmond",
      region: "Richmond",
      niche: "Arts education, classes, memberships, exhibitions",
      angle:
        "When class registration and post-registration follow-up live in different tools, re-enrollment usually depends on somebody remembering to chase it.",
    }),
  },
  {
    _id: "lead-candidate-branch-museum",
    ...defaults,
    businessName: "The Branch Museum of Design",
    niche: "Museum, design education, venue rentals, events",
    city: "Richmond",
    region: "Richmond",
    address: "2501 Monument Avenue, Richmond, VA 23220",
    phone: "(804) 655-6055",
    email: null,
    contactUrl: "https://branchmuseum.org/contact/",
    website: "https://branchmuseum.org/",
    sourceUrl: "https://branchmuseum.org/",
    fitScore: 74,
    currentSnapshot: "Active museum with exhibitions, design programming, membership, donations, and venue rentals.",
    gapAssessment: "Events, rentals, membership, and donations appear to be separate conversion paths.",
    howCel3CanHelp: "An interactive venue/event inquiry system could improve rental intake and give staff a clearer pipeline.",
    ...outreach({
      businessName: "The Branch Museum of Design",
      city: "Richmond",
      region: "Richmond",
      niche: "Museum, design education, venue rentals, events",
      angle:
        "Rentals, membership, donations, and event RSVPs converting through separate paths usually means the follow-up queue lives in someone's head.",
    }),
  },
  {
    _id: "lead-candidate-the-broadberry",
    ...defaults,
    businessName: "The Broadberry",
    niche: "Live music venue, ticketing, private events",
    city: "Richmond",
    region: "Richmond",
    address: "2729 W Broad Street, Richmond, VA 23220",
    phone: "(804) 353-1888",
    email: null,
    contactUrl: "https://thebroadberry.com/contact/",
    website: "https://thebroadberry.com/",
    sourceUrl: "https://thebroadberry.com/",
    fitScore: 76,
    currentSnapshot: "Active live music venue with events calendar, ticketing, and private event opportunities.",
    gapAssessment: "Venue, event, and private booking inquiries can become high-value leads if tracked cleanly.",
    howCel3CanHelp: "A private-events lead dashboard and automated follow-up flow could help convert inquiries faster.",
    ...outreach({
      businessName: "The Broadberry",
      city: "Richmond",
      region: "Richmond",
      niche: "Live music venue, ticketing, private events",
      angle:
        "Private-event inquiries are the highest-dollar messages hitting your inbox, and they're usually competing with everything else in it.",
    }),
  },
  {
    _id: "lead-candidate-the-camel",
    ...defaults,
    businessName: "The Camel",
    niche: "Live music venue, food, events",
    city: "Richmond",
    region: "Richmond",
    address: "1621 W Broad Street, Richmond, VA 23220",
    phone: "(804) 353-4901",
    email: null,
    contactUrl: "https://thecamel.org/contact/",
    website: "https://thecamel.org/",
    sourceUrl: "https://thecamel.org/",
    fitScore: 72,
    currentSnapshot: "Active Richmond venue with live shows, food, and event listings.",
    gapAssessment: "Shows, booking requests, and customer engagement are natural candidates for lightweight automation.",
    howCel3CanHelp: "A better booking/request workflow could keep artist, promoter, and private event communication organized.",
    ...outreach({
      businessName: "The Camel",
      city: "Richmond",
      region: "Richmond",
      niche: "Live music venue, food, events",
      angle:
        "Artist, promoter, and private-event requests tend to get buried in shared inboxes precisely because show weeks are the busy ones.",
    }),
  },
  {
    _id: "lead-candidate-lewis-ginter",
    ...defaults,
    businessName: "Lewis Ginter Botanical Garden",
    niche: "Botanical garden, memberships, events, education",
    city: "Richmond",
    region: "Richmond",
    address: "1800 Lakeside Avenue, Richmond, VA 23228",
    phone: "(804) 262-9887",
    email: null,
    contactUrl: "https://www.lewisginter.org/contact-us/",
    website: "https://www.lewisginter.org/",
    sourceUrl: "https://www.lewisginter.org/",
    fitScore: 79,
    currentSnapshot: "Active garden with admission, memberships, events, education, rentals, and donations.",
    gapAssessment: "Large volume of program and visitor data could be clearer through operational dashboards.",
    howCel3CanHelp: "A unified events, member, and education dashboard could reveal trends and improve follow-up.",
    ...outreach({
      businessName: "Lewis Ginter Botanical Garden",
      city: "Richmond",
      region: "Richmond",
      niche: "Botanical garden, memberships, events, education",
      angle:
        "With admissions, memberships, education, rentals, and donations all in motion, month-end reporting usually means stitching numbers together from five systems by hand.",
    }),
  },
  {
    _id: "lead-candidate-maymont",
    ...defaults,
    businessName: "Maymont",
    niche: "Museum, park, events, memberships, education",
    city: "Richmond",
    region: "Richmond",
    address: "1700 Hampton Street, Richmond, VA 23220",
    phone: "(804) 358-7166",
    email: null,
    contactUrl: "https://maymont.org/contact/",
    website: "https://maymont.org/",
    sourceUrl: "https://maymont.org/",
    fitScore: 77,
    currentSnapshot: "Active destination with events, programs, memberships, donations, and rentals.",
    gapAssessment: "Program, rental, and donor experiences likely touch multiple systems and staff workflows.",
    howCel3CanHelp: "A visitor/program operations interface could make inquiries, bookings, and engagement easier to track.",
    ...outreach({
      businessName: "Maymont",
      city: "Richmond",
      region: "Richmond",
      niche: "Museum, park, events, memberships, education",
      angle:
        "Programs, rentals, memberships, and donor touchpoints crossing that many systems usually means staff carry the connections between them manually.",
    }),
  },
  {
    _id: "lead-candidate-art-works-richmond",
    ...defaults,
    businessName: "Art Works Richmond",
    niche: "Gallery, artist studios, classes, events",
    city: "Richmond",
    region: "Richmond",
    address: "320 Hull Street, Richmond, VA 23224",
    phone: "(804) 291-1400",
    email: null,
    contactUrl: "https://artworksrva.com/contact/",
    website: "https://artworksrva.com/",
    sourceUrl: "https://artworksrva.com/",
    fitScore: 71,
    currentSnapshot: "Active gallery and studio business with exhibitions, events, and artist-facing services.",
    gapAssessment: "Artist inquiries, exhibit submissions, classes, and event promotion are operationally connected.",
    howCel3CanHelp: "A submission and artist relationship dashboard could simplify intake and follow-up.",
    ...outreach({
      businessName: "Art Works Richmond",
      city: "Richmond",
      region: "Richmond",
      niche: "Gallery, artist studios, classes, events",
      angle:
        "Artist submissions, studio inquiries, and event leads arriving through the same contact form usually means triage and follow-up happen by hand.",
    }),
  },
  {
    _id: "lead-candidate-virginia-rep",
    ...defaults,
    businessName: "Virginia Repertory Theatre",
    niche: "Theatre, education, tickets, donors",
    city: "Richmond",
    region: "Richmond",
    address: "114 W Broad Street, Richmond, VA 23220",
    phone: "(804) 282-2620",
    email: null,
    contactUrl: "https://va-rep.org/contact.html",
    website: "https://va-rep.org/",
    sourceUrl: "https://va-rep.org/",
    fitScore: 75,
    currentSnapshot: "Active theatre organization with performances, education programs, tickets, and donor engagement.",
    gapAssessment: "Ticket buyers, donors, education families, and group audiences have different journeys.",
    howCel3CanHelp: "A segmented engagement dashboard could help tailor follow-up across tickets, donors, and programs.",
    ...outreach({
      businessName: "Virginia Repertory Theatre",
      city: "Richmond",
      region: "Richmond",
      niche: "Theatre, education, tickets, donors",
      angle:
        "Ticket buyers, education families, donors, and group sales are four different journeys, and keeping their follow-up straight across separate tools is real staff time.",
    }),
  },
  {
    _id: "lead-candidate-studio-bamboo",
    ...defaults,
    businessName: "Studio Bamboo Institute of Yoga",
    niche: "Yoga studio, memberships, classes, teacher training",
    city: "Virginia Beach",
    region: "Tidewater",
    address: "Virginia Beach, VA",
    phone: null,
    email: null,
    contactUrl: "https://www.studiobambooyoga.com/contact",
    website: "https://www.studiobambooyoga.com/",
    sourceUrl: "https://www.studiobambooyoga.com/",
    fitScore: 83,
    currentSnapshot: "Active yoga studio with class scheduling, workshops, trainings, and membership-style services.",
    gapAssessment: "Wellness studios often need better retention dashboards and automated member journeys.",
    howCel3CanHelp: "A client dashboard could surface class attendance, lapsed members, training leads, and follow-up priorities.",
    ...outreach({
      businessName: "Studio Bamboo Institute of Yoga",
      city: "Virginia Beach",
      region: "Tidewater",
      niche: "Yoga studio, memberships, classes, teacher training",
      angle:
        "Intro-offer conversion and lapsed-member win-backs are usually where studios leak the most revenue — not for lack of intent, but because nobody has time to work the list by hand.",
    }),
  },
  {
    _id: "lead-candidate-hot-house-yoga",
    ...defaults,
    businessName: "Hot House Yoga",
    niche: "Yoga and fitness studio, memberships, workshops",
    city: "Virginia Beach",
    region: "Tidewater",
    address: "Virginia Beach and Norfolk, VA",
    phone: null,
    email: null,
    contactUrl: "https://hothouseyogi.com/contact/",
    website: "https://hothouseyogi.com/",
    sourceUrl: "https://hothouseyogi.com/",
    fitScore: 81,
    currentSnapshot: "Active regional yoga brand with multiple locations, classes, workshops, and memberships.",
    gapAssessment: "Multi-location wellness operations benefit from clearer performance and retention data.",
    howCel3CanHelp: "A location-level dashboard could connect attendance, memberships, instructors, and automated reactivation.",
    ...outreach({
      businessName: "Hot House Yoga",
      city: "Virginia Beach",
      region: "Tidewater",
      niche: "Yoga and fitness studio, memberships, workshops",
      angle:
        "Across multiple locations, comparing attendance, retention, and instructor load usually means someone rebuilds the same spreadsheet every month.",
    }),
  },
  {
    _id: "lead-candidate-the-muse-writers-center",
    ...defaults,
    businessName: "The Muse Writers Center",
    niche: "Creative education, classes, memberships, nonprofit",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "2200 Colonial Avenue, Suite 3, Norfolk, VA 23517",
    phone: null,
    email: null,
    contactUrl: "https://the-muse.org/contact/",
    website: "https://the-muse.org/",
    sourceUrl: "https://the-muse.org/",
    fitScore: 77,
    currentSnapshot: "Active writing center with classes, events, memberships, and community programming.",
    gapAssessment: "Class registration, member engagement, and event participation could be connected more clearly.",
    howCel3CanHelp: "A program dashboard could show class demand, student history, and follow-up opportunities.",
    ...outreach({
      businessName: "The Muse Writers Center",
      city: "Norfolk",
      region: "Hampton Roads",
      niche: "Creative education, classes, memberships, nonprofit",
      angle:
        "When class demand, student history, and member follow-up live in separate tools, re-enrollment tends to run on memory instead of signals.",
    }),
  },
  {
    _id: "lead-candidate-norfolk-botanical-garden",
    ...defaults,
    businessName: "Norfolk Botanical Garden",
    niche: "Botanical garden, memberships, events, education",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "6700 Azalea Garden Road, Norfolk, VA 23518",
    phone: "(757) 441-5830",
    email: null,
    contactUrl: "https://norfolkbotanicalgarden.org/contact/",
    website: "https://norfolkbotanicalgarden.org/",
    sourceUrl: "https://norfolkbotanicalgarden.org/",
    fitScore: 79,
    currentSnapshot: "Active garden with tickets, memberships, events, education, and rentals.",
    gapAssessment: "Events, memberships, education, and visitor services create many conversion paths.",
    howCel3CanHelp: "A visitor and events dashboard could consolidate inquiry, membership, and program data.",
    ...outreach({
      businessName: "Norfolk Botanical Garden",
      city: "Norfolk",
      region: "Hampton Roads",
      niche: "Botanical garden, memberships, events, education",
      angle:
        "Tickets, memberships, education, and rentals each report cleanly on their own; getting one picture of a visitor across all four usually doesn't happen without manual work.",
    }),
  },
  {
    _id: "lead-candidate-virginia-zoo",
    ...defaults,
    businessName: "Virginia Zoo",
    niche: "Zoo, memberships, education, events",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "3500 Granby Street, Norfolk, VA 23504",
    phone: "(757) 441-2374",
    email: null,
    contactUrl: "https://virginiazoo.org/contact/",
    website: "https://virginiazoo.org/",
    sourceUrl: "https://virginiazoo.org/",
    fitScore: 76,
    currentSnapshot: "Active visitor attraction with admission, memberships, education, events, and donations.",
    gapAssessment: "Membership, event, donor, and education touchpoints could be easier to visualize together.",
    howCel3CanHelp: "A lifecycle dashboard could help staff see visitor-to-member and donor engagement opportunities.",
    ...outreach({
      businessName: "Virginia Zoo",
      city: "Norfolk",
      region: "Hampton Roads",
      niche: "Zoo, memberships, education, events",
      angle:
        "The visitor-to-member-to-donor path crosses at least three systems, so the natural upgrade moments usually pass by without anyone seeing them.",
    }),
  },
  {
    _id: "lead-candidate-nauticus",
    ...defaults,
    businessName: "Nauticus",
    niche: "Museum, maritime attraction, events, education",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "1 Waterside Drive, Norfolk, VA 23510",
    phone: "(757) 664-1000",
    email: null,
    contactUrl: "https://nauticus.org/contact/",
    website: "https://nauticus.org/",
    sourceUrl: "https://nauticus.org/",
    fitScore: 78,
    currentSnapshot: "Active maritime museum and attraction with tickets, memberships, events, and education programs.",
    gapAssessment: "Visitor, event, field trip, and membership paths create a strong need for integrated reporting.",
    howCel3CanHelp: "An interactive operations dashboard could tie ticketing, memberships, school groups, and event inquiries together.",
    ...outreach({
      businessName: "Nauticus",
      city: "Norfolk",
      region: "Hampton Roads",
      niche: "Museum, maritime attraction, events, education",
      angle:
        "Field-trip requests, group bookings, and event inquiries are high-value intake that usually gets handled like ordinary email.",
    }),
  },
  {
    _id: "lead-candidate-hermitage-museum",
    ...defaults,
    businessName: "Hermitage Museum and Gardens",
    niche: "Museum, gardens, classes, venue rentals",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "7637 North Shore Road, Norfolk, VA 23505",
    phone: "(757) 423-2052",
    email: null,
    contactUrl: "https://thehermitagemuseum.org/contact/",
    website: "https://thehermitagemuseum.org/",
    sourceUrl: "https://thehermitagemuseum.org/",
    fitScore: 74,
    currentSnapshot: "Active museum and garden with events, education, exhibitions, and wedding/private rental potential.",
    gapAssessment: "Venue rental and program inquiries can be better tracked as leads.",
    howCel3CanHelp: "A rental and program inquiry system could improve response speed and conversion tracking.",
    ...outreach({
      businessName: "Hermitage Museum and Gardens",
      city: "Norfolk",
      region: "Hampton Roads",
      niche: "Museum, gardens, classes, venue rentals",
      angle:
        "Wedding and rental inquiries age fast — when they sit in a shared inbox, response time quietly decides the booking.",
    }),
  },
  {
    _id: "lead-candidate-chrysler-museum",
    ...defaults,
    businessName: "Chrysler Museum of Art",
    niche: "Museum, memberships, events, classes",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "1 Memorial Place, Norfolk, VA 23510",
    phone: "(757) 664-6200",
    email: null,
    contactUrl: "https://chrysler.org/contact/",
    website: "https://chrysler.org/",
    sourceUrl: "https://chrysler.org/",
    fitScore: 75,
    currentSnapshot: "Active art museum with exhibitions, memberships, events, education, and glass studio programming.",
    gapAssessment: "Program discovery, member engagement, and event conversion could benefit from connected data.",
    howCel3CanHelp: "A member and program engagement dashboard could expose where audiences are converting or dropping off.",
    ...outreach({
      businessName: "Chrysler Museum of Art",
      city: "Norfolk",
      region: "Hampton Roads",
      niche: "Museum, memberships, events, classes",
      angle:
        "Between exhibitions, memberships, classes, and the glass studio, the same person can show up in four datasets — and connecting them usually falls to whoever has time.",
    }),
  },
  {
    _id: "lead-candidate-zeiders-theater",
    ...defaults,
    businessName: "Zeiders American Dream Theater",
    niche: "Performing arts, tickets, education, events",
    city: "Virginia Beach",
    region: "Tidewater",
    address: "4509 Commerce Street, Virginia Beach, VA 23462",
    phone: "(757) 499-0317",
    email: null,
    contactUrl: "https://thez.org/contact/",
    website: "https://thez.org/",
    sourceUrl: "https://thez.org/",
    fitScore: 73,
    currentSnapshot: "Active theater with performances, classes, rentals, and community programming.",
    gapAssessment: "Ticketing, education, rental inquiries, and donor engagement are related but often live in separate systems.",
    howCel3CanHelp: "A performing arts dashboard could centralize audience, class, rental, and donor signals.",
    ...outreach({
      businessName: "Zeiders American Dream Theater",
      city: "Virginia Beach",
      region: "Tidewater",
      niche: "Performing arts, tickets, education, events",
      angle:
        "Ticketing, classes, rental inquiries, and donor engagement usually live in separate systems, which means the follow-up between them is a manual job.",
    }),
  },
  {
    _id: "lead-candidate-mermaid-winery",
    ...defaults,
    businessName: "Mermaid Winery",
    niche: "Restaurant, winery, events, private bookings",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "330 W 22nd Street, Norfolk, VA 23517",
    phone: "(757) 233-4155",
    email: null,
    contactUrl: "https://www.mermaidwinery.com/contact/",
    website: "https://www.mermaidwinery.com/",
    sourceUrl: "https://www.mermaidwinery.com/",
    fitScore: 70,
    currentSnapshot: "Active winery and restaurant with reservations, events, private dining, and ecommerce-style potential.",
    gapAssessment: "Private event inquiries and customer retention can be easy to lose without a simple lead workflow.",
    howCel3CanHelp: "A private events and VIP follow-up dashboard could help convert inquiries and repeat customers.",
    ...outreach({
      businessName: "Mermaid Winery",
      city: "Norfolk",
      region: "Hampton Roads",
      niche: "Restaurant, winery, events, private bookings",
      angle:
        "Private-dining inquiries and repeat-guest outreach handled from the inbox means the busiest weeks are exactly when follow-up slips.",
    }),
  },
];
