import type { LeadCandidateInput } from "./types";

function emailBody(name: string, niche: string, help: string) {
  return [
    "<p>Hello,</p>",
    `<p>I was reviewing ${name} and noticed the kind of public-facing ${niche.toLowerCase()} work you are already doing in Virginia.</p>`,
    `<p>CEL3 Interactive builds custom web applications, client portals, dashboards, and AI-enhanced systems for teams that need their website to do more than display information. ${help}</p>`,
    "<p>If it is useful, I can put together a short systems assessment showing where your current digital flow could be tightened up and what would have the highest return.</p>",
    "<p>Would you be open to a quick conversation next week?</p>",
    "<p>Best,<br>CEL3 Interactive</p>",
  ].join("");
}

const defaults = {
  status: "review" as const,
  openStatus: "open" as const,
  leadSource: "Researched seed list",
  notes: null,
  reviewedAt: null,
  approvedPipelineContactId: null,
  emailedAt: null,
};

export const researchedSeedLeads: LeadCandidateInput[] = [
  {
    _id: "lead-candidate-richmond-ballet",
    ...defaults,
    businessName: "Richmond Ballet",
    niche: "Performing arts, education, memberships, events",
    city: "Richmond",
    region: "Richmond",
    address: "407 East Canal Street, Richmond, VA 23219",
    phone: "(804) 344-0906",
    email: null,
    contactUrl: "https://richmondballet.com/contact-us/",
    website: "https://richmondballet.com/",
    sourceUrl: "https://richmondballet.com/",
    fitScore: 82,
    currentSnapshot: "Active performing arts organization with school, performances, ticketing, donations, rentals, and news signup.",
    gapAssessment: "Multiple user paths appear spread across tickets, school, donations, rentals, and events.",
    howCel3CanHelp: "A cleaner audience portal and event/school dashboard could connect ticketing, classes, donations, and follow-up in one system.",
    emailSubject: "Idea for Richmond Ballet's digital audience flow",
    emailBodyHtml: emailBody("Richmond Ballet", "performing arts", "A unified dashboard could make audience, student, donor, and event interactions easier to track."),
  },
  {
    _id: "lead-candidate-studio-two-three",
    ...defaults,
    businessName: "Studio Two Three",
    niche: "Arts nonprofit, workshops, memberships, community programs",
    city: "Richmond",
    region: "Richmond",
    address: "109 W 15th Street, Richmond, VA 23224",
    phone: null,
    email: null,
    contactUrl: "https://studiotwothree.org/pages/contact",
    website: "https://studiotwothree.org/",
    sourceUrl: "https://studiotwothree.org/",
    fitScore: 78,
    currentSnapshot: "Active arts organization with classes, membership, events, shop, and community programs.",
    gapAssessment: "Workshop, member, donor, and retail paths create a strong case for better operational visibility.",
    howCel3CanHelp: "A member/class operations console could centralize signups, attendance, donor touchpoints, and program performance.",
    emailSubject: "A systems idea for Studio Two Three",
    emailBodyHtml: emailBody("Studio Two Three", "arts programming", "Your mix of classes, memberships, and community programs is a good fit for a custom operations dashboard."),
  },
  {
    _id: "lead-candidate-visual-arts-center-richmond",
    ...defaults,
    businessName: "Visual Arts Center of Richmond",
    niche: "Arts education, classes, memberships, exhibitions",
    city: "Richmond",
    region: "Richmond",
    address: "1812 W Main Street, Richmond, VA 23220",
    phone: "(804) 353-0094",
    email: null,
    contactUrl: "https://www.visarts.org/contact/",
    website: "https://www.visarts.org/",
    sourceUrl: "https://www.visarts.org/",
    fitScore: 80,
    currentSnapshot: "Active arts center with classes, events, exhibitions, youth programs, and memberships.",
    gapAssessment: "Class discovery and engagement could benefit from more personalized navigation and post-registration follow-up.",
    howCel3CanHelp: "A class/member dashboard could help surface enrollment trends, automate reminders, and clarify program performance.",
    emailSubject: "Improving class and member flows at VisArts",
    emailBodyHtml: emailBody("Visual Arts Center of Richmond", "arts education", "A tailored class and membership dashboard could make program operations easier to understand and act on."),
  },
  {
    _id: "lead-candidate-branch-museum",
    ...defaults,
    businessName: "The Branch Museum of Design",
    niche: "Museum, design education, venue rentals, events",
    city: "Richmond",
    region: "Richmond",
    address: "2501 Monument Avenue, Richmond, VA 23220",
    phone: "(804) 655-6055",
    email: null,
    contactUrl: "https://branchmuseum.org/contact/",
    website: "https://branchmuseum.org/",
    sourceUrl: "https://branchmuseum.org/",
    fitScore: 74,
    currentSnapshot: "Active museum with exhibitions, design programming, membership, donations, and venue rentals.",
    gapAssessment: "Events, rentals, membership, and donations appear to be separate conversion paths.",
    howCel3CanHelp: "An interactive venue/event inquiry system could improve rental intake and give staff a clearer pipeline.",
    emailSubject: "A digital intake idea for The Branch",
    emailBodyHtml: emailBody("The Branch Museum of Design", "museum and venue", "A smarter event and rental intake flow could reduce back-and-forth and expose better lead data."),
  },
  {
    _id: "lead-candidate-the-broadberry",
    ...defaults,
    businessName: "The Broadberry",
    niche: "Live music venue, ticketing, private events",
    city: "Richmond",
    region: "Richmond",
    address: "2729 W Broad Street, Richmond, VA 23220",
    phone: "(804) 353-1888",
    email: null,
    contactUrl: "https://thebroadberry.com/contact/",
    website: "https://thebroadberry.com/",
    sourceUrl: "https://thebroadberry.com/",
    fitScore: 76,
    currentSnapshot: "Active live music venue with events calendar, ticketing, and private event opportunities.",
    gapAssessment: "Venue, event, and private booking inquiries can become high-value leads if tracked cleanly.",
    howCel3CanHelp: "A private-events lead dashboard and automated follow-up flow could help convert inquiries faster.",
    emailSubject: "Private event lead flow for The Broadberry",
    emailBodyHtml: emailBody("The Broadberry", "live events", "A custom inquiry-to-booking dashboard could make private event leads easier to manage."),
  },
  {
    _id: "lead-candidate-the-camel",
    ...defaults,
    businessName: "The Camel",
    niche: "Live music venue, food, events",
    city: "Richmond",
    region: "Richmond",
    address: "1621 W Broad Street, Richmond, VA 23220",
    phone: "(804) 353-4901",
    email: null,
    contactUrl: "https://thecamel.org/contact/",
    website: "https://thecamel.org/",
    sourceUrl: "https://thecamel.org/",
    fitScore: 72,
    currentSnapshot: "Active Richmond venue with live shows, food, and event listings.",
    gapAssessment: "Shows, booking requests, and customer engagement are natural candidates for lightweight automation.",
    howCel3CanHelp: "A better booking/request workflow could keep artist, promoter, and private event communication organized.",
    emailSubject: "Booking workflow idea for The Camel",
    emailBodyHtml: emailBody("The Camel", "live venue", "A simple booking and follow-up system could help keep event requests from getting buried."),
  },
  {
    _id: "lead-candidate-lewis-ginter",
    ...defaults,
    businessName: "Lewis Ginter Botanical Garden",
    niche: "Botanical garden, memberships, events, education",
    city: "Richmond",
    region: "Richmond",
    address: "1800 Lakeside Avenue, Richmond, VA 23228",
    phone: "(804) 262-9887",
    email: null,
    contactUrl: "https://www.lewisginter.org/contact-us/",
    website: "https://www.lewisginter.org/",
    sourceUrl: "https://www.lewisginter.org/",
    fitScore: 79,
    currentSnapshot: "Active garden with admission, memberships, events, education, rentals, and donations.",
    gapAssessment: "Large volume of program and visitor data could be clearer through operational dashboards.",
    howCel3CanHelp: "A unified events, member, and education dashboard could reveal trends and improve follow-up.",
    emailSubject: "A member and events dashboard idea",
    emailBodyHtml: emailBody("Lewis Ginter Botanical Garden", "visitor experience", "An intelligent dashboard could connect membership, programs, rentals, and visitor engagement."),
  },
  {
    _id: "lead-candidate-maymont",
    ...defaults,
    businessName: "Maymont",
    niche: "Museum, park, events, memberships, education",
    city: "Richmond",
    region: "Richmond",
    address: "1700 Hampton Street, Richmond, VA 23220",
    phone: "(804) 358-7166",
    email: null,
    contactUrl: "https://maymont.org/contact/",
    website: "https://maymont.org/",
    sourceUrl: "https://maymont.org/",
    fitScore: 77,
    currentSnapshot: "Active destination with events, programs, memberships, donations, and rentals.",
    gapAssessment: "Program, rental, and donor experiences likely touch multiple systems and staff workflows.",
    howCel3CanHelp: "A visitor/program operations interface could make inquiries, bookings, and engagement easier to track.",
    emailSubject: "Systems idea for Maymont's visitor programs",
    emailBodyHtml: emailBody("Maymont", "visitor programs", "A custom dashboard could help connect events, rentals, programs, and donor engagement."),
  },
  {
    _id: "lead-candidate-art-works-richmond",
    ...defaults,
    businessName: "Art Works Richmond",
    niche: "Gallery, artist studios, classes, events",
    city: "Richmond",
    region: "Richmond",
    address: "320 Hull Street, Richmond, VA 23224",
    phone: "(804) 291-1400",
    email: null,
    contactUrl: "https://artworksrva.com/contact/",
    website: "https://artworksrva.com/",
    sourceUrl: "https://artworksrva.com/",
    fitScore: 71,
    currentSnapshot: "Active gallery and studio business with exhibitions, events, and artist-facing services.",
    gapAssessment: "Artist inquiries, exhibit submissions, classes, and event promotion are operationally connected.",
    howCel3CanHelp: "A submission and artist relationship dashboard could simplify intake and follow-up.",
    emailSubject: "Artist intake and event workflow idea",
    emailBodyHtml: emailBody("Art Works Richmond", "gallery and artist services", "A custom intake system could organize artist submissions, event leads, and follow-up."),
  },
  {
    _id: "lead-candidate-virginia-rep",
    ...defaults,
    businessName: "Virginia Repertory Theatre",
    niche: "Theatre, education, tickets, donors",
    city: "Richmond",
    region: "Richmond",
    address: "114 W Broad Street, Richmond, VA 23220",
    phone: "(804) 282-2620",
    email: null,
    contactUrl: "https://va-rep.org/contact.html",
    website: "https://va-rep.org/",
    sourceUrl: "https://va-rep.org/",
    fitScore: 75,
    currentSnapshot: "Active theatre organization with performances, education programs, tickets, and donor engagement.",
    gapAssessment: "Ticket buyers, donors, education families, and group audiences have different journeys.",
    howCel3CanHelp: "A segmented engagement dashboard could help tailor follow-up across tickets, donors, and programs.",
    emailSubject: "Digital audience flow idea for Virginia Rep",
    emailBodyHtml: emailBody("Virginia Repertory Theatre", "performing arts", "A data interface could make ticket, donor, and education engagement easier to segment."),
  },
  {
    _id: "lead-candidate-studio-bamboo",
    ...defaults,
    businessName: "Studio Bamboo Institute of Yoga",
    niche: "Yoga studio, memberships, classes, teacher training",
    city: "Virginia Beach",
    region: "Tidewater",
    address: "Virginia Beach, VA",
    phone: null,
    email: null,
    contactUrl: "https://www.studiobambooyoga.com/contact",
    website: "https://www.studiobambooyoga.com/",
    sourceUrl: "https://www.studiobambooyoga.com/",
    fitScore: 83,
    currentSnapshot: "Active yoga studio with class scheduling, workshops, trainings, and membership-style services.",
    gapAssessment: "Wellness studios often need better retention dashboards and automated member journeys.",
    howCel3CanHelp: "A client dashboard could surface class attendance, lapsed members, training leads, and follow-up priorities.",
    emailSubject: "Member retention idea for Studio Bamboo",
    emailBodyHtml: emailBody("Studio Bamboo Institute of Yoga", "wellness studio", "A retention-focused dashboard could help spot member patterns and automate thoughtful outreach."),
  },
  {
    _id: "lead-candidate-hot-house-yoga",
    ...defaults,
    businessName: "Hot House Yoga",
    niche: "Yoga and fitness studio, memberships, workshops",
    city: "Virginia Beach",
    region: "Tidewater",
    address: "Virginia Beach and Norfolk, VA",
    phone: null,
    email: null,
    contactUrl: "https://hothouseyogi.com/contact/",
    website: "https://hothouseyogi.com/",
    sourceUrl: "https://hothouseyogi.com/",
    fitScore: 81,
    currentSnapshot: "Active regional yoga brand with multiple locations, classes, workshops, and memberships.",
    gapAssessment: "Multi-location wellness operations benefit from clearer performance and retention data.",
    howCel3CanHelp: "A location-level dashboard could connect attendance, memberships, instructors, and automated reactivation.",
    emailSubject: "Multi-location retention dashboard idea",
    emailBodyHtml: emailBody("Hot House Yoga", "multi-location wellness", "A custom dashboard could compare locations, attendance, and member engagement without adding admin overhead."),
  },
  {
    _id: "lead-candidate-the-muse-writers-center",
    ...defaults,
    businessName: "The Muse Writers Center",
    niche: "Creative education, classes, memberships, nonprofit",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "2200 Colonial Avenue, Suite 3, Norfolk, VA 23517",
    phone: null,
    email: null,
    contactUrl: "https://the-muse.org/contact/",
    website: "https://the-muse.org/",
    sourceUrl: "https://the-muse.org/",
    fitScore: 77,
    currentSnapshot: "Active writing center with classes, events, memberships, and community programming.",
    gapAssessment: "Class registration, member engagement, and event participation could be connected more clearly.",
    howCel3CanHelp: "A program dashboard could show class demand, student history, and follow-up opportunities.",
    emailSubject: "A class engagement dashboard idea for The Muse",
    emailBodyHtml: emailBody("The Muse Writers Center", "creative education", "A class and member dashboard could help connect student journeys across programs and events."),
  },
  {
    _id: "lead-candidate-norfolk-botanical-garden",
    ...defaults,
    businessName: "Norfolk Botanical Garden",
    niche: "Botanical garden, memberships, events, education",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "6700 Azalea Garden Road, Norfolk, VA 23518",
    phone: "(757) 441-5830",
    email: null,
    contactUrl: "https://norfolkbotanicalgarden.org/contact/",
    website: "https://norfolkbotanicalgarden.org/",
    sourceUrl: "https://norfolkbotanicalgarden.org/",
    fitScore: 79,
    currentSnapshot: "Active garden with tickets, memberships, events, education, and rentals.",
    gapAssessment: "Events, memberships, education, and visitor services create many conversion paths.",
    howCel3CanHelp: "A visitor and events dashboard could consolidate inquiry, membership, and program data.",
    emailSubject: "A dashboard idea for garden programs and events",
    emailBodyHtml: emailBody("Norfolk Botanical Garden", "visitor experience", "A custom system could make programs, events, memberships, and visitor follow-up easier to manage."),
  },
  {
    _id: "lead-candidate-virginia-zoo",
    ...defaults,
    businessName: "Virginia Zoo",
    niche: "Zoo, memberships, education, events",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "3500 Granby Street, Norfolk, VA 23504",
    phone: "(757) 441-2374",
    email: null,
    contactUrl: "https://virginiazoo.org/contact/",
    website: "https://virginiazoo.org/",
    sourceUrl: "https://virginiazoo.org/",
    fitScore: 76,
    currentSnapshot: "Active visitor attraction with admission, memberships, education, events, and donations.",
    gapAssessment: "Membership, event, donor, and education touchpoints could be easier to visualize together.",
    howCel3CanHelp: "A lifecycle dashboard could help staff see visitor-to-member and donor engagement opportunities.",
    emailSubject: "Visitor-to-member dashboard idea for Virginia Zoo",
    emailBodyHtml: emailBody("Virginia Zoo", "visitor attraction", "A lifecycle dashboard could clarify how visitors, members, events, and donors connect."),
  },
  {
    _id: "lead-candidate-nauticus",
    ...defaults,
    businessName: "Nauticus",
    niche: "Museum, maritime attraction, events, education",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "1 Waterside Drive, Norfolk, VA 23510",
    phone: "(757) 664-1000",
    email: null,
    contactUrl: "https://nauticus.org/contact/",
    website: "https://nauticus.org/",
    sourceUrl: "https://nauticus.org/",
    fitScore: 78,
    currentSnapshot: "Active maritime museum and attraction with tickets, memberships, events, and education programs.",
    gapAssessment: "Visitor, event, field trip, and membership paths create a strong need for integrated reporting.",
    howCel3CanHelp: "An interactive operations dashboard could tie ticketing, memberships, school groups, and event inquiries together.",
    emailSubject: "Digital operations idea for Nauticus",
    emailBodyHtml: emailBody("Nauticus", "museum and attraction", "An intelligent interface could help connect visitor, member, event, and education data."),
  },
  {
    _id: "lead-candidate-hermitage-museum",
    ...defaults,
    businessName: "Hermitage Museum and Gardens",
    niche: "Museum, gardens, classes, venue rentals",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "7637 North Shore Road, Norfolk, VA 23505",
    phone: "(757) 423-2052",
    email: null,
    contactUrl: "https://thehermitagemuseum.org/contact/",
    website: "https://thehermitagemuseum.org/",
    sourceUrl: "https://thehermitagemuseum.org/",
    fitScore: 74,
    currentSnapshot: "Active museum and garden with events, education, exhibitions, and wedding/private rental potential.",
    gapAssessment: "Venue rental and program inquiries can be better tracked as leads.",
    howCel3CanHelp: "A rental and program inquiry system could improve response speed and conversion tracking.",
    emailSubject: "Rental inquiry workflow idea for Hermitage",
    emailBodyHtml: emailBody("Hermitage Museum and Gardens", "museum and venue", "A custom inquiry workflow could help manage event, rental, and program leads."),
  },
  {
    _id: "lead-candidate-chrysler-museum",
    ...defaults,
    businessName: "Chrysler Museum of Art",
    niche: "Museum, memberships, events, classes",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "1 Memorial Place, Norfolk, VA 23510",
    phone: "(757) 664-6200",
    email: null,
    contactUrl: "https://chrysler.org/contact/",
    website: "https://chrysler.org/",
    sourceUrl: "https://chrysler.org/",
    fitScore: 75,
    currentSnapshot: "Active art museum with exhibitions, memberships, events, education, and glass studio programming.",
    gapAssessment: "Program discovery, member engagement, and event conversion could benefit from connected data.",
    howCel3CanHelp: "A member and program engagement dashboard could expose where audiences are converting or dropping off.",
    emailSubject: "Member engagement dashboard idea",
    emailBodyHtml: emailBody("Chrysler Museum of Art", "museum programming", "A tailored dashboard could make membership, program, and event engagement easier to act on."),
  },
  {
    _id: "lead-candidate-zeiders-theater",
    ...defaults,
    businessName: "Zeiders American Dream Theater",
    niche: "Performing arts, tickets, education, events",
    city: "Virginia Beach",
    region: "Tidewater",
    address: "4509 Commerce Street, Virginia Beach, VA 23462",
    phone: "(757) 499-0317",
    email: null,
    contactUrl: "https://thez.org/contact/",
    website: "https://thez.org/",
    sourceUrl: "https://thez.org/",
    fitScore: 73,
    currentSnapshot: "Active theater with performances, classes, rentals, and community programming.",
    gapAssessment: "Ticketing, education, rental inquiries, and donor engagement are related but often live in separate systems.",
    howCel3CanHelp: "A performing arts dashboard could centralize audience, class, rental, and donor signals.",
    emailSubject: "Audience and program dashboard idea for The Z",
    emailBodyHtml: emailBody("Zeiders American Dream Theater", "performing arts", "A custom dashboard could connect tickets, education, rentals, and community engagement."),
  },
  {
    _id: "lead-candidate-mermaid-winery",
    ...defaults,
    businessName: "Mermaid Winery",
    niche: "Restaurant, winery, events, private bookings",
    city: "Norfolk",
    region: "Hampton Roads",
    address: "330 W 22nd Street, Norfolk, VA 23517",
    phone: "(757) 233-4155",
    email: null,
    contactUrl: "https://www.mermaidwinery.com/contact/",
    website: "https://www.mermaidwinery.com/",
    sourceUrl: "https://www.mermaidwinery.com/",
    fitScore: 70,
    currentSnapshot: "Active winery and restaurant with reservations, events, private dining, and ecommerce-style potential.",
    gapAssessment: "Private event inquiries and customer retention can be easy to lose without a simple lead workflow.",
    howCel3CanHelp: "A private events and VIP follow-up dashboard could help convert inquiries and repeat customers.",
    emailSubject: "Private event lead flow idea for Mermaid Winery",
    emailBodyHtml: emailBody("Mermaid Winery", "restaurant and event", "A custom private-event lead flow could help organize inquiries and follow-up."),
  },
];
