export const DEFAULT_LEAD_SEARCH_LOCATIONS = [
  "Richmond VA",
  "Henrico VA",
  "Midlothian VA",
  "Chesterfield VA",
  "Glen Allen VA",
  "Short Pump VA",
  "Mechanicsville VA",
  "Ashland VA",
  "Norfolk VA",
  "Virginia Beach VA",
  "Chesapeake VA",
  "Portsmouth VA",
  "Suffolk VA",
  "Hampton VA",
  "Newport News VA",
  "Williamsburg VA",
  "Yorktown VA",
  "Hampton Roads VA",
];

export const US_CANADA_LEAD_SEARCH_LOCATIONS = [
  "United States",
  "Canada",
];

export const US_LEAD_SEARCH_LOCATIONS = [
  "United States",
];

export const CANADA_LEAD_SEARCH_LOCATIONS = [
  "Canada",
];

export const NORTH_AMERICA_LEAD_SEARCH_LOCATIONS = [
  "North America",
];

export const US_NORTHEAST_LEAD_SEARCH_LOCATIONS = [
  "Northeast US",
];

export const US_SOUTHEAST_LEAD_SEARCH_LOCATIONS = [
  "Southeast US",
];

export const US_MIDWEST_LEAD_SEARCH_LOCATIONS = [
  "Midwest US",
];

export const US_SOUTHWEST_LEAD_SEARCH_LOCATIONS = [
  "Southwest US",
];

export const US_WEST_LEAD_SEARCH_LOCATIONS = [
  "West US",
];

export const US_NORTHEAST_LEAD_SEARCH_MARKETS = [
  "New York NY",
  "Boston MA",
  "Philadelphia PA",
  "Pittsburgh PA",
  "Newark NJ",
  "Jersey City NJ",
  "Buffalo NY",
  "Rochester NY",
  "Albany NY",
  "Providence RI",
  "Hartford CT",
  "New Haven CT",
  "Portland ME",
  "Burlington VT",
  "Manchester NH",
];

export const US_SOUTHEAST_LEAD_SEARCH_MARKETS = [
  "Washington DC",
  "Baltimore MD",
  "Richmond VA",
  "Virginia Beach VA",
  "Norfolk VA",
  "Chesapeake VA",
  "Raleigh NC",
  "Durham NC",
  "Charlotte NC",
  "Greensboro NC",
  "Winston-Salem NC",
  "Charleston SC",
  "Columbia SC",
  "Atlanta GA",
  "Savannah GA",
  "Jacksonville FL",
  "Miami FL",
  "Tampa FL",
  "Orlando FL",
  "St. Petersburg FL",
  "Nashville TN",
  "Memphis TN",
  "Knoxville TN",
  "Louisville KY",
  "New Orleans LA",
  "Baton Rouge LA",
  "Birmingham AL",
  "Huntsville AL",
  "Jackson MS",
];

export const US_MIDWEST_LEAD_SEARCH_MARKETS = [
  "Chicago IL",
  "Indianapolis IN",
  "Fort Wayne IN",
  "Detroit MI",
  "Grand Rapids MI",
  "Columbus OH",
  "Cleveland OH",
  "Cincinnati OH",
  "Toledo OH",
  "Milwaukee WI",
  "Madison WI",
  "Minneapolis MN",
  "Saint Paul MN",
  "St. Louis MO",
  "Kansas City MO",
  "Omaha NE",
  "Wichita KS",
  "Des Moines IA",
  "Fargo ND",
  "Sioux Falls SD",
];

export const US_SOUTHWEST_LEAD_SEARCH_MARKETS = [
  "Houston TX",
  "San Antonio TX",
  "Dallas TX",
  "Fort Worth TX",
  "Austin TX",
  "El Paso TX",
  "Arlington TX",
  "Corpus Christi TX",
  "Laredo TX",
  "Oklahoma City OK",
  "Tulsa OK",
  "Phoenix AZ",
  "Tucson AZ",
  "Mesa AZ",
  "Chandler AZ",
  "Scottsdale AZ",
  "Glendale AZ",
  "Albuquerque NM",
  "Santa Fe NM",
];

export const US_WEST_LEAD_SEARCH_MARKETS = [
  "Los Angeles CA",
  "San Diego CA",
  "San Jose CA",
  "San Francisco CA",
  "Fresno CA",
  "Sacramento CA",
  "Long Beach CA",
  "Oakland CA",
  "Bakersfield CA",
  "Anaheim CA",
  "Riverside CA",
  "Stockton CA",
  "Irvine CA",
  "Chula Vista CA",
  "Seattle WA",
  "Spokane WA",
  "Tacoma WA",
  "Portland OR",
  "Eugene OR",
  "Denver CO",
  "Colorado Springs CO",
  "Aurora CO",
  "Las Vegas NV",
  "Henderson NV",
  "Reno NV",
  "Salt Lake City UT",
  "Boise ID",
  "Honolulu HI",
  "Anchorage AK",
];

export const US_NATIONWIDE_LEAD_SEARCH_MARKETS = [
  "New York NY",
  "Los Angeles CA",
  "Chicago IL",
  "Houston TX",
  "Phoenix AZ",
  "Philadelphia PA",
  "San Antonio TX",
  "San Diego CA",
  "Dallas TX",
  "San Jose CA",
  "Austin TX",
  "Jacksonville FL",
  "Fort Worth TX",
  "Columbus OH",
  "Charlotte NC",
  "San Francisco CA",
  "Indianapolis IN",
  "Seattle WA",
  "Denver CO",
  "Washington DC",
  "Boston MA",
  "El Paso TX",
  "Nashville TN",
  "Detroit MI",
  "Oklahoma City OK",
  "Portland OR",
  "Las Vegas NV",
  "Memphis TN",
  "Louisville KY",
  "Baltimore MD",
  "Milwaukee WI",
  "Albuquerque NM",
  "Tucson AZ",
  "Fresno CA",
  "Sacramento CA",
  "Atlanta GA",
  "Kansas City MO",
  "Colorado Springs CO",
  "Miami FL",
  "Raleigh NC",
  "Omaha NE",
  "Long Beach CA",
  "Virginia Beach VA",
  "Oakland CA",
  "Minneapolis MN",
  "Tulsa OK",
  "Tampa FL",
  "Arlington TX",
  "New Orleans LA",
  "Wichita KS",
  "Cleveland OH",
  "Bakersfield CA",
  "Aurora CO",
  "Anaheim CA",
  "Honolulu HI",
  "Riverside CA",
  "Corpus Christi TX",
  "Lexington KY",
  "Henderson NV",
  "Stockton CA",
  "Saint Paul MN",
  "Cincinnati OH",
  "St. Louis MO",
  "Pittsburgh PA",
  "Greensboro NC",
  "Anchorage AK",
  "Plano TX",
  "Orlando FL",
  "Irvine CA",
  "Newark NJ",
  "Durham NC",
  "Chula Vista CA",
  "Toledo OH",
  "Fort Wayne IN",
  "St. Petersburg FL",
  "Laredo TX",
  "Jersey City NJ",
  "Chandler AZ",
  "Madison WI",
  "Lubbock TX",
  "Scottsdale AZ",
  "Reno NV",
  "Buffalo NY",
  "Gilbert AZ",
  "Glendale AZ",
  "North Las Vegas NV",
  "Winston-Salem NC",
  "Chesapeake VA",
  "Norfolk VA",
  "Fremont CA",
  "Garland TX",
  "Irving TX",
  "Hialeah FL",
  "Richmond VA",
  "Boise ID",
  "Spokane WA",
  "Baton Rouge LA",
  "Tacoma WA",
  "San Bernardino CA",
  "Modesto CA",
];

export const CANADA_NATIONWIDE_LEAD_SEARCH_MARKETS = [
  "Toronto ON",
  "Montreal QC",
  "Vancouver BC",
  "Calgary AB",
  "Edmonton AB",
  "Ottawa ON",
  "Winnipeg MB",
  "Quebec City QC",
  "Hamilton ON",
  "Kitchener ON",
  "London ON",
  "Victoria BC",
  "Halifax NS",
  "Oshawa ON",
  "Windsor ON",
  "Saskatoon SK",
  "Regina SK",
  "St. Catharines ON",
  "Kelowna BC",
  "Barrie ON",
  "Sherbrooke QC",
  "Guelph ON",
  "Kingston ON",
  "Abbotsford BC",
  "Sudbury ON",
  "Trois-Rivieres QC",
  "Moncton NB",
  "Brantford ON",
  "Saint John NB",
  "Peterborough ON",
];

export const OPEN_LEAD_SEARCH_CATEGORIES = [
  "business",
  "company",
  "local business",
  "small business",
  "service business",
  "professional services",
  "home services",
  "retail business",
];

export const DEFAULT_LEAD_SEARCH_CATEGORIES = [
  "yoga studio",
  "fitness studio",
  "personal training gym",
  "pilates studio",
  "barre studio",
  "dance studio",
  "martial arts school",
  "wellness center",
  "spa",
  "day spa",
  "med spa",
  "massage therapy",
  "chiropractor",
  "physical therapy clinic",
  "nutritionist",
  "counseling practice",
  "therapy practice",
  "private medical practice",
  "dental practice",
  "orthodontist",
  "veterinary clinic",
  "dog groomer",
  "pet boarding",
  "child care center",
  "preschool",
  "tutoring center",
  "music school",
  "art school",
  "arts education",
  "performing arts",
  "museum",
  "gallery",
  "nonprofit",
  "community organization",
  "event venue",
  "wedding venue",
  "private event venue",
  "conference venue",
  "coworking space",
  "restaurant private events",
  "catering company",
  "bakery",
  "coffee shop",
  "boutique",
  "salon",
  "barbershop",
  "esthetician",
  "photographer",
  "florist",
  "interior designer",
  "landscaper",
  "home cleaning service",
  "HVAC contractor",
  "plumber",
  "electrician",
  "roofing contractor",
  "remodeling contractor",
  "auto repair shop",
  "car detailing",
];
