export const DEFAULT_LEAD_SEARCH_LOCATIONS = [
  "Richmond VA",
  "Henrico VA",
  "Midlothian VA",
  "Chesterfield VA",
  "Glen Allen VA",
  "Short Pump VA",
  "Mechanicsville VA",
  "Ashland VA",
  "Norfolk VA",
  "Virginia Beach VA",
  "Chesapeake VA",
  "Portsmouth VA",
  "Suffolk VA",
  "Hampton VA",
  "Newport News VA",
  "Williamsburg VA",
  "Yorktown VA",
  "Hampton Roads VA",
];

export const DEFAULT_LEAD_SEARCH_CATEGORIES = [
  "yoga studio",
  "fitness studio",
  "personal training gym",
  "pilates studio",
  "barre studio",
  "dance studio",
  "martial arts school",
  "wellness center",
  "spa",
  "day spa",
  "med spa",
  "massage therapy",
  "chiropractor",
  "physical therapy clinic",
  "nutritionist",
  "counseling practice",
  "therapy practice",
  "private medical practice",
  "dental practice",
  "orthodontist",
  "veterinary clinic",
  "dog groomer",
  "pet boarding",
  "child care center",
  "preschool",
  "tutoring center",
  "music school",
  "art school",
  "arts education",
  "performing arts",
  "museum",
  "gallery",
  "nonprofit",
  "community organization",
  "event venue",
  "wedding venue",
  "private event venue",
  "conference venue",
  "coworking space",
  "restaurant private events",
  "catering company",
  "bakery",
  "coffee shop",
  "boutique",
  "salon",
  "barbershop",
  "esthetician",
  "photographer",
  "florist",
  "interior designer",
  "landscaper",
  "home cleaning service",
  "HVAC contractor",
  "plumber",
  "electrician",
  "roofing contractor",
  "remodeling contractor",
  "auto repair shop",
  "car detailing",
];
